# Generated by Django 5.0.6 on 2024-06-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Completos', 'Completos'), ('Hamburguesas', 'Hamburguesas'), ('Pizzas', 'Pizzas'), ('Papas Fritas', 'Papas Fritas'), ('Bebidas', 'Bebidas')], default='Sin Seleccionar', max_length=50)),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
