# Generated by Django 5.0.6 on 2024-06-26 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Ingrese solo letras y espacios.')]),
        ),
    ]
