# Generated by Django 5.0.6 on 2024-07-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_pedido_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('prefijo_telefono', models.CharField(choices=[('+56', '+56 Chile'), ('+34', '+34 España'), ('+52', '+52 México'), ('+54', '+54 Argentina'), ('+1', '+1 EE.UU.')], max_length=5)),
                ('direccion_facturacion_igual', models.BooleanField(default=False)),
            ],
        ),
    ]
