# Generated by Django 5.0.6 on 2024-07-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_datospago'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospago',
            name='pedido',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='aplicacion.pedido'),
        ),
    ]
