# Generated by Django 5.0.6 on 2024-07-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_detallepedido_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='prefijo_telefono',
            field=models.CharField(choices=[('+56', '+56 Chile'), ('+34', '+34 España'), ('+52', '+52 México'), ('+54', '+54 Argentina'), ('+1', '+1 EE.UU.')], default=0, max_length=5),
            preserve_default=False,
        ),
    ]
